nodeLinker: hoisted

publicHoistPattern:
  - '*prisma*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  lefthook: true
  prisma: true
  sharp: true

blockExoticSubdeps: false

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
